version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
      docker: 18
    commands:
      - echo Entered the install phase
      - apt-get update -y
  
  pre_build:
    commands:
      - echo logging in to AWS ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION) 
      - REPOSITORY_URI=805468111780.dkr.ecr.us-east-2.amazonaws.com/firstregister
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  
  build:
    commands:
      - echo Entered the build phase
      - echo Build started on `date`
      - ant compile jar war
      - echo Building the Docker image
      - echo Build started on `date`
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  
  post_build:
    commands:
      - echo Entered the post_build phase
      - echo Build completed on `date`
      - echo Pushing the Docker image
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"leadapp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files: imagedefinitions.json
cache:
  paths:
    - '/root/.m2/**/*'
